name: zezis_printing
description: Plugin that allows Flutter apps to generate and print documents

version: 0.0.1
repository: https://github.com/joseaugustoaquino/zezis_widget
homepage: https://github.com/joseaugustoaquino

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  web: ^0.5.1
  image: ^4.1.0
  bidi: ^2.0.10
  crypto: ^3.0.0
  archive: ^3.4.0
  vector_math: ^2.1.0
  xml: ">=6.3.0 <7.0.0"
  ffi: ">=1.1.0 <3.0.0"
  meta: ">=1.3.0 <2.0.0"
  http: ">=0.13.0 <2.0.0"
  barcode: ">=2.2.3 <3.0.0"
  path_parsing: ">=0.2.0 <2.0.0"
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: net.nfet.flutter.printing
        pluginClass: PrintingPlugin
      ios:
        pluginClass: PrintingPlugin
      linux:
        pluginClass: PrintingPlugin
      macos:
        pluginClass: PrintingPlugin
      web:
        fileName: printing_web.dart
        pluginClass: PrintingPlugin
      windows:
        pluginClass: PrintingPlugin